### PR TITLE
Key alphabet: Remove unusual characters

### LINKED ISSUE #19: Avoid using characters not commonly found in URLs
Whenever I send a file through f.bain, a parenthesis can appear in the token, which makes the link highlight only partially in many messaging apps (e.g. Signal).

I think it would be good to remove parentheses and other unusual characters from the allowed token chars, for accessibility but at a small token strength cost.

### PR DESCRIPTION
**Pull request by tarneaux**
This fixes #19.
I'm keeping `-`, `.` and `_` since they are very common characters in URLs.

### CODE REVIEW

**Comment by tarneaux** [comment]
OK, PR is ready to merge.

**Comment by bain3** [comment]
I'd remove all the special characters. `.` sometimes gets interpreted as the end of a sentence in chats. It really doesn't matter that much and I think it will be much nicer to have pure alpha-num urls.

**Comment by tarneaux** [comment]
OK, tested and works on my server.

**Comment by bain3** [comment]
Thanks!

**Pull request merged**
